---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: istio-root-ca
  namespace: cert-manager
spec:
  ca:
    secretName: istio-root-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster1-cacerts
  namespace: istio-system
spec:
  secretName: cluster1-cacerts
  duration: 720h # 30d
  renewBefore: 360h # 15d
  commonName: cluster1.solo.io
  isCA: true
  usages:
    - digital signature
    - key encipherment
    - cert sign
  dnsNames:
    - cluster1.solo.io
  # Issuer references are always required.
  issuerRef:
    kind: ClusterIssuer
    name: istio-root-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vm-cacerts
  namespace: istio-system
spec:
  secretName: vm-cacerts
  duration: 720h # 30d
  renewBefore: 360h # 15d
  commonName: vms.solo.io
  isCA: true
  usages:
    - digital signature
    - key encipherment
    - cert sign
  dnsNames:
    - vms.solo.io
  # Issuer references are always required.
  issuerRef:
    kind: ClusterIssuer
    name: istio-root-ca
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vm-istio-ca
  namespace: istio-system
spec:
  ca:
    secretName: vm-cacerts
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vm-proxy
  namespace: istio-system
spec:
  secretName: vm-proxy
  duration: 720h # 30d
  renewBefore: 360h # 15d
  commonName: envoy-proxy
  isCA: false
  usages:
    - client auth
    - server auth
  uris:
    - spiffe://vms.solo.io/ns/vm/sa/vm-1
  # Issuer references are always required.
  issuerRef:
    kind: Issuer
    name: vm-istio-ca
